### PR TITLE
improves pt-br translations

### PR DESCRIPTION
**Pull request by gugacavalieri**
## ✅ New Quote Checklist
- [x] The quote(s) added are in alphabetical order by author's first name and not ❌ duplicates.
- [x] The quote(s) added are about **learning a foreign language**.
- [x] The sentence attribute does not have inner quotation marks, and is ended with a period.
- [x] Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.

### CODE REVIEW

**Comment by gugacavalieri** [comment]
Hi @jayehernandez !

I am a native speaker from BR and I saw that a lot of `pt-br` quotes can be improved. I opened a Draft PR just to make sure that I am on the right track here.

What do you think? Should I proceed and review the other quotes?

Cheers! :smile: :brazil:

**Comment by jayehernandez** [comment]
Hi @gugacavalieri, yes thank you! Changes look good so far, please let me know if you are going to be requesting a review for this! :)

**Comment by gugacavalieri** [comment]
Hi @jayehernandez ! I will!

Just wondering if I should finish the whole file first ... What do you think? :)

**Comment by jayehernandez** [comment]
I think that would be better! Are you participating in hacktoberfest?

**Comment by gugacavalieri** [comment]
> I think that would be better! Are you participating in hacktoberfest?

Sounds good ...

I am! Have a few days to go ;)

**Comment by jayehernandez** [comment]
Cool!! Good luck 🙌

**Comment by gugacavalieri** [comment]
Hi @jayehernandez ! This one is good to go :smile:

**Comment by jayehernandez** [comment]
Thanks for working on this @gugacavalieri!!

@all-contributors please add @gugacavalieri for translation

**Pull request merged**
