### PR TITLE
ported to firefox tested with firefox extension compatibility test

### PR DESCRIPTION
**Pull request by rookiemonkey**
Below is the step-by-step that i've done to figure out how port letra to firefox. It turns out that we only need to add something on manifest.json.
	
1. setup the server with necessary environment variables (eg: unsplash access key) and run it in the background and leave him alone 😁 hehe
	
2. built the application first $ npm run build
	
3. go to chrome://extensions/ with dev mode on
	
4. in order to test the compatibility to firefox, we need the extension's .crx file. To do this, we will pack extension using chrome, choose client/dist folder and it will output a .crx file

5. went to https://www.extensiontest.com/ to test firefox compatibility
	
	OUTPUT:
	- extension is compatible but with errors mostly with manifest.json file
		 

6. temporarily installed the extension on firefox (latest version 83.0) by following this instructions: 
(i selected the manifest.json inside the dist folder) 
https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/
	
	OUTPUT:
	- throws an error about the manifest file
	- tried to reload the tab, manifest.json error goes away, loading svg is showing and doesnt proceed
	- sometimes goes through the loader, however list of languages is empty which suppose to be provided by the server
		 
	

7. changed the manifest.json and built the application again $ npm run build
	
8. did the same thing on steps 5/6 and its now working on firefox
	
	OUTPUT:
	- no errors on https://www.extensiontest.com/ but with some warnings about security
	- its working on firefox when installed temporarily the same way it works on chrome
		
		
			
**NOTE: 
         - the browser specific setting added on manifest.json is  used to distinguish this add-on from any other Firefox add-on.
          https://extensionworkshop.com/documentation/develop/extensions-and-the-add-on-id/
         - The last step would be publishing letra on addons.mozilla.org (AMO)**

### CODE REVIEW

**Comment by Kvaibhav01** [comment]
Great work @rookiemonkey! We had a Firefox extension in mind but didn't know about this method. 😮 Thanks! 

@jayehernandez I'm excited to take a look at how it works on Firefox, open to testing it too. 😁

**Comment by jayehernandez** [comment]
@Kvaibhav01 feel free to do so! Let me know if you'll be needing anything for testing. :)

**Comment by rookiemonkey** [comment]
@Kvaibhav01  @jayehernandez  I really appreciate it ezpecially im a beginner ❤️ Thank you so much. If there is something wrong upon submitting to AMO ill be very happy to help again and research on what are the things needed to be done ☺️

**Comment by rookiemonkey** [comment]
Hi @Kvaibhav01  and @jayehernandez I just checked it again and followed the same steps that i've created above. This is our output after changing the manifest.json temporarily installed on firefox dugger :100: 

screen

**Comment by Kvaibhav01** [comment]
@rookiemonkey looks good! After the recent output, can you list down things which are not working at the moment?

**Comment by rookiemonkey** [comment]
@Kvaibhav01 Thank you so much :D so far, everything is working fine as long as the browser specific setting is existing on manifest.json. I think it is needed when an extension needs access to storage which in letra's case, it needs it. After adding the browser specific setting, i've encountered no bugs and eveything works just like how it is working on chrome. However, firefox extension test tool shows some security warnings which i hope will not affect the submission to AMO. Check this blob https://www.extensiontest.com/test/d031fe00-3474-11eb-bd04-154faeee22f8 and click on "Report Details" or you can download the zip folder that i've attached.

[letra-report.zip](https://github.com/jayehernandez/letra-extension/files/5627773/letra-report.zip)

**Comment by jayehernandez** [comment]
@rookiemonkey I've tested the extension on my end according to your instructions and it does work well! I saw the same security warnings and I do hope we'll be able to submit it even with these. In Chrome, I was able to explain why the `manifest.json` file contained those permissions. 

I was able to test:
- Responsive Voice API
- Refreshing the word for the day
- Adding / removing a language

image

The only thing that I am concerned about is the fact that the URL cannot be cleared by extensions. After researching on it though, there's no way to remove it.

@Kvaibhav01 let me know if you are able to test this out as well. After that, we can proceed with submitting it to the AMO for review. Exciting times, thank you for initiating once again, @rookiemonkey!

**Comment by Kvaibhav01** [comment]
Okay, will test it soon (in a day or two) and let you guys know how it goes. Looks like a positive start so far! 🥳

**Comment by rookiemonkey** [comment]
Hi @jayehernandez  and @Kvaibhav01  Sorry. I was so busy finishing my school project :). I've actually tried to research for the firefox extension URL and it seems like thats the way firefox handles their extensions. There is a similar chrome/firefox extension called 'Momentum' which behaves then way letra behaves when a user open a new tab. see [Momentum](https://get.momentumdash.help/hc/en-us/articles/115007780748-About-Momentum) However, I was not able to find any source code, specifically its manifest.json, related to Momentum rendering me to think that the extension is not an open source. One thing I tried too is installing Momentum on my firefox just to check if the URL looks like the one in Letra, however, Momentum is not working on my firefox, not sure if its me or just my browser. :D

**Comment by Kvaibhav01** [comment]
Hey, @rookiemonkey in my case Momentum isn't showing any URL while it's active. The browser is Firefox Developer Edition.


Screenshot 2020-12-04 at 8 15 46 PM

**Comment by rookiemonkey** [comment]
@Kvaibhav01 can you try to install letra temporarily and see if its the same. if its not and still shows the url with its extension ID, i hope there is way to extract the manifest. json of momentum. I havent tried installing it on firefox dev though. Ill try tomorrow after my class.

**Comment by Kvaibhav01** [comment]
@rookiemonkey so here are the two screenshots. I followed your steps and got the following ~~weird~~  results...

As for the actual extension loading and working, it's sometimes working, and sometimes it isn't going past the loader screen. I get the same privacy issue on the extension test.

On the **Firefox Developer Edition** browser:

Screenshot 2020-12-04 at 11 24 27 PM

I'm not able to see any URL of the extension.

On the **usual Firefox browser**:

Screenshot 2020-12-04 at 11 25 16 PM

Here, I can see the URL.

**Comment by rookiemonkey** [comment]
@Kvaibhav01 hmmm that is weird. Can you try to open the console, reload the extension's tab and see if there is any errors?. Regarding the URL I think it is really how the firefox handles their extension. It is different when it comes to their browser's dev version. Can you also try to use momentum on the ordinary firefox and check its url?. Mine doesn't work im sorry

**Comment by jayehernandez** [comment]
@rookiemonkey @Kvaibhav01 for reference too, I tried installing Momentum on normal Firefox and it doesn't show the URL too. We can try to look into it after publishing to the AMO? (before announcing that we have an extension for Firefox 😅)

**Comment by Kvaibhav01** [comment]
There are no errors or serious issues when I open dev tools on the ordinary Firefox. I have refreshed the tab too:
Screenshot 2020-12-05 at 6 32 04 PM

On the ordinary Firefox, there is no URL:
Screenshot 2020-12-05 at 6 35 11 PM

**Comment by Kvaibhav01** [comment]
@jayehernandez yes, I think most of the important features of the extension are working as expected on Firefox? If yes, then surely we can take a look at how to fix the URL part later.

**Comment by rookiemonkey** [comment]
@jayehernandez  and @Kvaibhav01  I agree :+1: :100:

**Comment by jayehernandez** [comment]
@rookiemonkey @Kvaibhav01 great! I'll work on publishing the extension, will let you know when it's approved! :)

**Comment by jayehernandez** [comment]
Leaving an update here! I've submitted the `.crx` file over at AMO, will let you guys know once it has been reviewed.

image

**Review by jayehernandez — APPROVED** [review]

**Comment by jayehernandez** [comment]
Accepting this PR to place the code in master branch! They need to have the source code too so I'm getting the clean copy here on GitHub... my local one is messed up 😂

**Comment by jayehernandez** [comment]
Just so I don't forget too...

@all-contributors please add @rookiemonkey for code :D

**Pull request merged**
