### PR TITLE
Add inspirational quotes

### PR DESCRIPTION
**Pull request by PulkitAgg**
## ✅ New Quote Checklist
- [ ] The quote(s) added are in alphabetical order and not ❌ duplicates.
- [ ] The quote(s) added are about **learning a foreign language**.
- [ ] The sentence attribute does not have inner quotation marks, and is ended with a period.
- [ ] Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.

## ✅ New Language Checklist
- [ ] There is ❌ no assigned issue or pull request for this new language.
- [ ] ➕ Added a new JSON object in the `server/data/languages.json` file.
- [ ] Added the **voice** 🎤 attribute supported by ResponsiveVoice API.
- [ ] Added the **flag** 🏳 attribute in the format of the twemoji-awesome CSS syntax.
- [ ] Added the **romanization** attribute for appropriate languages.
- [ ] ➕ Created the `{language.json}` file inside the `server/data/words` folder containing the list of the 3000 words.
- [ ] Removed duplicates and noted 🗒 them in the Pull Request.
- [ ] Increment `currentLanguagesCount` in `client/src/store/index.js`
- [ ] Add new language in `README.md`

### CODE REVIEW

**Review by Kvaibhav01 — CHANGES_REQUESTED** [review]
Hey, @PulkitAgg please make sure you read the [contributing guidelines](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_quote.md#-checklist) before making a PR. You need to arrange these quotes alphabetically as others are arranged (according to the author's name) and make sure none of them are already in this file.

**Comment by PulkitAgg** [comment]
@Kvaibhav01 Thanks for your comment. I will update this PR

**Review by jayehernandez — CHANGES_REQUESTED** [review]
Quotes are not related to language learning, please read the guidelines for adding new quotes. :)

**Comment by PulkitAgg** [comment]
@jayehernandez I have updated the `quotes.json` file. Please review it again

**Review by jayehernandez — APPROVED** [review]

**Comment by jayehernandez** [comment]
Changes look good! Thank you for contributing to Letra ☀️, @PulkitAgg!! Appreciate your contribution to this open source project. 🥳

---

Continue supporting Letra by:
- Leaving a star ⭐️ for this GitHub repository
- Downloading the free [Chrome extension](https://chrome.google.com/webstore/detail/letra/cjodkkjokggcaeacdhjliobekbnnmoio) and leaving a review
- Upvoting the [ProductHunt page](https://www.producthunt.com/posts/letra-2)

**Pull request merged**
