### PR TITLE
Adding a tool to automatically populate the first column of the trans…

### PR DESCRIPTION
**Pull request by WyldWanderer**
…lation Google Sheet

## ✅ New Quote Checklist
- [ ] The quote(s) added are in alphabetical order by author's first name and not ❌ duplicates.
- [ ] The quote(s) added are about **learning a foreign language**.
- [ ] The sentence attribute does not have inner quotation marks, and is ended with a period.
- [ ] Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.

## ✅ New Language Checklist
- [ ] There is ❌ no assigned issue or pull request for this new language.
- [ ] ➕ Added a new JSON object in the `server/data/languages.json` file.
- [ ] Added the **voice** 🎤 attribute supported by ResponsiveVoice API.
- [ ] Added the **flag** 🏳 attribute in the format of the twemoji-awesome CSS syntax.
- [ ] Added the **romanization** attribute for appropriate languages.
- [ ] ➕ Created the `{language.json}` file inside the `server/data/words` folder containing the list of the 3000 words.
- [ ] Removed duplicates and noted 🗒 them in the Pull Request.
- [ ] Increment `currentLanguagesCount` in `client/src/store/index.js`
- [ ] Add new language in `README.md`

### CODE REVIEW

**Comment by jayehernandez** [comment]
Thanks for opening this! I’m not sure I follow but how would this work? The changes I see only imports ezsheets but doesn’t do anything after?

**Comment by WyldWanderer** [comment]
> Thanks for opening this! I’m not sure I follow but how would this work? The changes I see only imports ezsheets but doesn’t do anything after?

Whoops! My apologies, I'm new to contributing to other projects and added the wrong file to the push, I'll create a new pull request with the correct file as soon as possible.

**Comment by WyldWanderer** [comment]
@jayehernandez @Kvaibhav01 Made a second commit with the correct file, let me know if I need to do anything else

**Comment by jayehernandez** [comment]
Thanks @WyldWanderer! Can you reference this file in the [docs](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_language.md). You can add it as a note in #2 of the [Adding Words](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_language.md#adding-words) section.

Will merge after!

**Comment by WyldWanderer** [comment]
> Thanks @WyldWanderer! Can you reference this file in the [docs](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_language.md)? You can add it as a note in #2 of the [Adding Words](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_language.md#adding-words) section.
> 
> Will merge after!

@jayehernandez done!

**Review by jayehernandez — APPROVED** [review]
Thank you for contributing to Letra ☀️, @WyldWanderer!! Appreciate your contribution to this open source project. 🥳

---

Continue supporting Letra by:
- Leaving a star ⭐️ for this GitHub repository
- Downloading the free [Chrome extension](https://chrome.google.com/webstore/detail/letra/cjodkkjokggcaeacdhjliobekbnnmoio) and leaving a review
- Upvoting the [ProductHunt page](https://www.producthunt.com/posts/letra-2)

**Comment by jayehernandez** [comment]
@all-contributors please add @WyldWanderer for code

**Pull request merged**
