### PR TITLE
Added quote on Margaret Atwood

### PR DESCRIPTION
**Pull request by Harshi7016**
## ✅ New Quote Checklist
- [ ] The quote(s) added are in alphabetical order and not ❌ duplicates.
- [ ] The quote(s) added are about **learning a foreign language**.
- [ ] The sentence attribute does not have inner quotation marks, and is ended with a period.
- [ ] Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.

## ✅ New Language Checklist
- [ ] There is ❌ no assigned issue or pull request for this new language.
- [ ] ➕ Added a new JSON object in the `server/data/languages.json` file.
- [ ] Added the **voice** 🎤 attribute supported by ResponsiveVoice API.
- [ ] Added the **flag** 🏳 attribute in the format of the twemoji-awesome CSS syntax.
- [ ] Added the **romanization** attribute for appropriate languages.
- [ ] ➕ Created the `{language.json}` file inside the `server/data/words` folder containing the list of the 3000 words.
- [ ] Removed duplicates and noted 🗒 them in the Pull Request.
- [ ] Increment `currentLanguagesCount` in `client/src/store/index.js`
- [ ] Add new language in `README.md`

### CODE REVIEW

**Review by Kvaibhav01 — CHANGES_REQUESTED** [review]
Hi, @Harshi7016 thanks for the PR. You need to include a quote that matches the [contribution guidelines](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_quote.md#-checklist). Quotes should be about learning a new language.

**Comment by Harshi7016** [comment]
Ok, sure I will search for other quotes which relates more to speech.. I really liked this quote because of its deep meaning 
Shall I remove that and update a different quote?

**Comment by Kvaibhav01** [comment]
@Harshi7016 wait till I confirm this.

**Comment by Harshi7016** [comment]
@Kvaibhav01 , Sorry for not noticing your comment and working on the changes, however I have saved the quote locally and if required , please mention here I can add and raise PR anytime.
Thanks for the comment. 
{
    "author": "Margaret Atwood",
    "sentence": "Touch comes before sight, before speech. It is the first language and the last, and it always tells the truth."
  },
This is for your reference :)

**Comment by Harshi7016** [comment]
What is your thought on new quote @Kvaibhav01 ?

**Comment by Kvaibhav01** [comment]
@Harshi7016 it's on point. It will be approved soon I guess.

**Comment by Harshi7016** [comment]
Awesome 😊

**Review by Kvaibhav01 — APPROVED** [review]

**Comment by jayehernandez** [comment]
Thank you for contributing to Letra ☀️, @Harshi7016!! Appreciate your contribution to this open source project. 🥳

---

Continue supporting Letra by:
- Leaving a star ⭐️ for this GitHub repository
- Downloading the free [Chrome extension](https://chrome.google.com/webstore/detail/letra/cjodkkjokggcaeacdhjliobekbnnmoio) and leaving a review
- Upvoting the [ProductHunt page](https://www.producthunt.com/posts/letra-2)

**Comment by Harshi7016** [comment]
Great news, Am already on it

**Pull request merged**
