### PR TITLE
Update quotes.json

### PR DESCRIPTION
**Pull request by sonuraghuwanshi**
This is my first contribution to open-source. Hope I have met the expectations. I have added a quote by Desmond Tutu.

### CODE REVIEW

**Comment by jayehernandez** [comment]
Congrats on your first contribution, @sonuraghuwanshi! 

Hope you can change the `base branch` to `develop` instead of `master` before I merge. Thanks!

**Comment by sonuraghuwanshi** [comment]
Can you please tell me in detail. Which base branch? I am new to the contributions so I am learning.

**Comment by jayehernandez** [comment]
No worries! If you press the `Edit` button in the top right corner of this Pull Request, you can actually change the `base` (the one with the dropdown right below the title). Just change it from master to develop.

Let me know if you need any further help!

**Comment by sonuraghuwanshi** [comment]
@jayehernandez I have changed the base from master to develop. Can you please answer the following question.
What is the base?
Is it important to change it to develop?
what's the difference in master and develop?

**Comment by jayehernandez** [comment]
Thanks for changing it @sonuraghuwanshi!

Base is the branch where you'll be merging the changes. So from your branch `patch-1`, you'll be merging it to my `develop` branch. 

The difference between the two is that the `master` branch is the code that's currently published on the Chrome Web Store (production code) and the `develop` branch is the code used for development and testing. As a practice, it is better to change it to develop so that we can test it out first before publishing it to production code -- to the users.

Hope this explains things :)

**Comment by jayehernandez** [comment]
Also merging your change!

@all-contributors please add @sonuraghuwanshi for content

**Pull request merged**
