### PR TITLE
add Chinese (Traditional) language

### PR DESCRIPTION
**Pull request by fanlan1210**
## ✅ New Language Checklist
- [x] There is ❌ no assigned issue or pull request for this new language.
- [x] ➕ Added a new JSON object in the `server/data/languages.json` file.
- [x] Added the **voice** 🎤 attribute supported by ResponsiveVoice API.
- [x] Added the **flag** 🏳 attribute in the format of the twemoji-awesome CSS syntax.
- [ ] Added the **romanization** attribute for appropriate languages.
- [x] ➕ Created the `{language.json}` file inside the `server/data/words` folder containing the list of the 3000 words.
- [x] Removed duplicates and noted 🗒 them in the Pull Request.
- [x] Increment `currentLanguagesCount` in `client/src/store/index.js`
- [x] Add new language in `README.md`

I am not sure should remove the words which have the same text but have different meaning and type.
If it should, please let me know, I will fix it.

### CODE REVIEW

**Comment by jayehernandez** [comment]
Hey @fanlan1210 can you give an example of such words so we can check?

**Comment by fanlan1210** [comment]
@jayehernandez for example, "discover" and "discovery" have the same Traditional Chinese text "發現".
But this word type can express a noun or a verb in some different scenarios.

**Comment by jayehernandez** [comment]
Got this! I'm good with keeping this for now.

**Comment by jayehernandez** [comment]
Thank you for contributing to Letra ☀️, @fanlan1210!! Appreciate your contribution to this open source project. 🥳

I'll be including this in the next release. 

---

Continue supporting Letra by:
- Leaving a star ⭐️ for this GitHub repository
- Downloading the free [Chrome extension](https://chrome.google.com/webstore/detail/letra/cjodkkjokggcaeacdhjliobekbnnmoio) and leaving a review
- Upvoting the [ProductHunt page](https://www.producthunt.com/posts/letra-2)

**Comment by jayehernandez** [comment]
@all-contributors please add @fanlan1210 for translation

**Pull request merged**
