### PR TITLE
Add quote by Kurt Tucholsky and fixed spacing

### PR DESCRIPTION
**Pull request by joelhart**

### CODE REVIEW

**Comment by joelhart** [comment]
@jayehernandez Question about functionality. When the 'new tab' page is refreshed via the browser (not to be mistaken from the extension refresh button), should it retain the current featured word or generate a new one upon refresh?

**Comment by jayehernandez** [comment]
> @jayehernandez Question about functionality. When the 'new tab' page is refreshed via the browser (not to be mistaken from the extension refresh button), should it retain the current featured word or generate a new one upon refresh?

Hey @joelhart, good question! The word will retain when the new tab page is refreshed. I didn’t want to cause any accidental refresh so that’s what the button is for.

**Comment by jayehernandez** [comment]
Thanks for contributing as well! 🥳 If you have any suggestions for features, please let me know!

@all-contributors please add @joelhart for content

**Comment by joelhart** [comment]
Thank you!! 

Currently if I refresh the page, or close the tab and reopen it, the featured word will be the same. The only way to get a new word is to click the refresh button.

I was just curious if the behavior I was seeing was planned or not. Is there any sort of auto/scheduled word reset implementation? This may be a potential functionality to consider.

**Comment by jayehernandez** [comment]
> @jayehernandez Thank you!!
> 
> Currently if I refresh the page, or close the tab and reopen it, the featured word will be the same. The only way to get a new word is to click the refresh button.
> 
> I was just curious if the behavior I was seeing was planned or not. Is there any sort of auto/scheduled word reset implementation? This may be a potential functionality to consider.

@joelhart Ahh yes, the word refreshes every 12 AM! This is so the user will be able to retain the featured word for that day when they open a new tab.

**Pull request merged**
