### PR TITLE
Update languages.json

### PR DESCRIPTION
**Pull request by OreOlad**
## ✅ New Quote Checklist
- [ ] The quote(s) added are in alphabetical order and not ❌ duplicates.
- [ ] The quote(s) added are about **learning a foreign language**.
- [ ] The sentence attribute does not have inner quotation marks, and is ended with a period.
- [ ] Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.

## ✅ New Language Checklist
- [ ] There is ❌ no assigned issue or pull request for this new language.
- [ ] ➕ Added a new JSON object in the `server/data/languages.json` file.
- [ ] Added the **voice** 🎤 attribute supported by ResponsiveVoice API.
- [ ] Added the **flag** 🏳 attribute in the format of the twemoji-awesome CSS syntax.
- [ ] Added the **romanization** attribute for appropriate languages.
- [ ] ➕ Created the `{language.json}` file inside the `server/data/words` folder containing the list of the 3000 words.
- [ ] Removed duplicates and noted 🗒 them in the Pull Request.
- [ ] Increment `currentLanguagesCount` in `client/src/store/index.js`
- [ ] Add new language in `README.md`

### CODE REVIEW

**Comment by jayehernandez** [comment]
Hey @OreOlad, if you’d like to add Portuguese as a supported language, you also have to translate the 3000 words aside from just updating language.json.

Let me know if you’re up to that! If not, I’ll be closing this PR and since it doesn’t follow the guidelines.

**Review by jayehernandez — CHANGES_REQUESTED** [review]
Please follow the checklist for adding a new language!

**Comment by jayehernandez** [comment]
Closing this PR for now, if you'd like to add Portuguese, please comment on #1 instead.

**Comment by OreOlad** [comment]
next pr will have all of the words translated👍

**Pull request closed without merging**
