### PR TITLE
Added New quotes

### PR DESCRIPTION
**Pull request by profread**
## ✅ New Quote Checklist
- [ ] The quote(s) added are in alphabetical order by author's first name and not ❌ duplicates.
- [ ] The quote(s) added are about **learning a foreign language**.
- [ ] The sentence attribute does not have inner quotation marks, and is ended with a period.
- [ ] Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.

## ✅ New Language Checklist
- [ ] There is ❌ no assigned issue or pull request for this new language.
- [ ] ➕ Added a new JSON object in the `server/data/languages.json` file.
- [ ] Added the **voice** 🎤 attribute supported by ResponsiveVoice API.
- [ ] Added the **flag** 🏳 attribute in the format of the twemoji-awesome CSS syntax.
- [ ] Added the **romanization** attribute for appropriate languages.
- [ ] ➕ Created the `{language.json}` file inside the `server/data/words` folder containing the list of the 3000 words.
- [ ] Removed duplicates and noted 🗒 them in the Pull Request.
- [ ] Increment `currentLanguagesCount` in `client/src/store/index.js`
- [ ] Add new language in `README.md`

### CODE REVIEW

**Review by jayehernandez — CHANGES_REQUESTED** [review]
Please don't change the format of the file, if you'd like to add quotes, only change the needed lines.

**Comment by jayehernandez** [comment]
Closing this but feel free to create another PR that follows the guidelines. :)

**Comment by profread** [comment]
Can i know how i altered the file format?

**Comment by jayehernandez** [comment]
@profread here's a sample, the spaces for each quote are changed.

image

**Comment by profread** [comment]
Okay but  i deleted this commit already

**Pull request closed without merging**
