### PR TITLE
Closes #154 - Add Tamil language

### LINKED ISSUE #154: 🌍 Add Tamil Language
I created a guide for adding a new language [here](https://github.com/jayehernandez/letra-extension/blob/master/docs/new_language.md). Also, if applicable, hope you can add the romanization attribute of the word.

Please go through the checklist so that you won’t miss anything!

References #1

### PR DESCRIPTION
**Pull request by kvharish**
## ✅ New Language Checklist
- [x] There is ❌ no assigned issue or pull request for this new language.
- [x] ➕ Added a new JSON object in the `server/data/languages.json` file.
- [x] Added the **voice** 🎤 attribute supported by ResponsiveVoice API.
- [x] Added the **flag** 🏳 attribute in the format of the twemoji-awesome CSS syntax.
- [x] Added the **romanization** attribute for appropriate languages.
- [x] ➕ Created the `{language.json}` file inside the `server/data/words` folder containing the list of the 3000 words.
- [x] Removed duplicates and noted 🗒 them in the Pull Request.
- [x] Increment `currentLanguagesCount` in `client/src/store/index.js`
- [x] Add new language in `README.md`

### CODE REVIEW

**Review by jayehernandez — CHANGES_REQUESTED** [review]
Thanks for taking this on! hope you can resolve merge conflicts and I'll be merging soon after. :)

**Comment by kvharish** [comment]
@jayehernandez I have resolved the conflicts.

**Review by jayehernandez — APPROVED** [review]

**Comment by jayehernandez** [comment]
Thank you for contributing to Letra ☀️, @kvharish!! Appreciate your contribution to this open source project. 🥳

I'll be including this in the next release!

---

Continue supporting Letra by:
- Leaving a star ⭐️ for this GitHub repository
- Downloading the free [Chrome extension](https://chrome.google.com/webstore/detail/letra/cjodkkjokggcaeacdhjliobekbnnmoio) and leaving a review
- Upvoting the [ProductHunt page](https://www.producthunt.com/posts/letra-2)

**Comment by jayehernandez** [comment]
@all-contributors please add @kvharish for translation

**Pull request merged**
