### PR TITLE
add quote by Martin Heidigger

### PR DESCRIPTION
**Pull request by tomhayes**
## ✅ New Quote Checklist
- [x] The quote(s) added are in alphabetical order by author's first name and not ❌ duplicates.
- [x] The quote(s) added are about **learning a foreign language**.
- [x] The sentence attribute does not have inner quotation marks, and is ended with a period.
- [x] Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.

### CODE REVIEW

**Review by Kvaibhav01 — CHANGES_REQUESTED** [review]
Thanks for the PR. Just remove the _PULL_REQUEST_TEMPLATE.md_ file from your PR. We just need the quote added in the _quotes.json_ file.

**Review by tomhayes — COMMENTED** [review]
Removed the pull request template as instructed

**Comment by tomhayes** [comment]
Sorry I think I misunderstood the instructions! Is this correct now? Thanks!

**Comment by tomhayes** [comment]
Oh... have I deleted the file rather than deleting my changes?! Sorry...

**Comment by jayehernandez** [comment]
@tomhayes please bring back the file 😅

**Comment by jayehernandez** [comment]
Closing stale PR

**Pull request closed without merging**
