### PR TITLE
corrected translation for hindi

### PR DESCRIPTION
**Pull request by shubhangi013**
Corrected the translation for Hindi.

### CODE REVIEW

**Review by Kvaibhav01 — COMMENTED** [review]
Thanks for the PR but both of these words in Hindi mean the same and no need to add an alternate word when already available.

Please close this PR and the other one too: #574

**Comment by shubhangi013** [comment]
'Vastav main' means 'in reality' doesn't it? 😅
virtually is the opposite of that.

**Comment by Kvaibhav01** [comment]
Here, the word 'virtually' is in general terms and that means "nearly; almost" which can also translate to "वास्तव में".

Google Search image

The word "आभासी रूप से" [translates more to the word "literally"](https://translate.google.com/?source=osdd&sl=hi&tl=en&text=%E0%A4%86%E0%A4%AD%E0%A4%BE%E0%A4%B8%E0%A5%80%20%E0%A4%B0%E0%A5%82%E0%A4%AA%20%E0%A4%B8%E0%A5%87&op=translate). 

There is not much difference between the two as when translated, both can be accepted. So, no need to correct it unless we use it in a specific sentence or with a different meaning (which is essentially out of the scope our this application).

**Comment by shubhangi013** [comment]
> Here, the word 'virtually' is in general terms and that means "nearly; almost" which can also translate to "वास्तव में".
> 
> Google Search image
> 
> The word "आभासी रूप से" [translates more to the word "literally"](https://translate.google.com/?source=osdd&sl=hi&tl=en&text=%E0%A4%86%E0%A4%AD%E0%A4%BE%E0%A4%B8%E0%A5%80%20%E0%A4%B0%E0%A5%82%E0%A4%AA%20%E0%A4%B8%E0%A5%87&op=translate).
> 
> There is not much difference between the two as when translated, both can be accepted. So, no need to correct it unless we use it in a specific sentence or with a different meaning (which is essentially out of the scope our this application).

Ooh ! I get it now. Thank you so much for this explanation. I'll close this PR.

**Pull request closed without merging**
