### PR TITLE
Add new quote by Tom Reynolds

### PR DESCRIPTION
**Pull request by bobsany16**
## ✅ New Quote Checklist
- [x] The quote(s) added are in alphabetical order and not ❌ duplicates.
- [x] The quote(s) added are about **learning a foreign language**.
- [x] The sentence attribute does not have inner quotation marks, and is ended with a period.
- [x] Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.

#13

### CODE REVIEW

**Comment by jayehernandez** [comment]
Thank you for contributing to Letra ☀️, @bobsany16!! Appreciate your contribution to this open source project. 🥳

---

Continue supporting Letra by:
- Leaving a star ⭐️ for this GitHub repository
- Downloading the free [Chrome extension](https://chrome.google.com/webstore/detail/letra/cjodkkjokggcaeacdhjliobekbnnmoio) and leaving a review
- Upvoting the [ProductHunt page](https://www.producthunt.com/posts/letra-2)

**Comment by bobsany16** [comment]
@jayehernandez Thank you for the awesome repo! Looking forward to adding my language - Vietnamese - on here.

**Comment by jayehernandez** [comment]
@bobsany16 cool, I'll be on the lookout for that!

**Comment by bobsany16** [comment]
@jayehernandez nevermind hahaha, somebody beat me to it #386

**Pull request merged**
