### PR TITLE
Add Alvin Toffler  quote

### PR DESCRIPTION
**Pull request by ming-tsai**

### CODE REVIEW

**Comment by ming-tsai** [comment]
> Please add a quote in alphabetical order. Thanks

Done, please check it out

**Comment by ming-tsai** [comment]
> Looks good. Thanks

Ho do I merge it?

**Comment by HarshPatel270698** [comment]
@jayehernandez will do it.

> 
> 
> > Looks good. Thanks
> 
> How do I merge it?

**Comment by jayehernandez** [comment]
Thanks for working on this @ming-tsai!

@all-contributors please add @ming-tsai for content

**Comment by jayehernandez** [comment]
Thanks as always for reviewing @HarshPatel270698!

**Pull request merged**
