### PR TITLE
Change languages options to use a multiple select dropdown

### PR DESCRIPTION
**Pull request by reginaalyssa**
Addresses Issue #434 

Change language options from checkboxes to multiple dropdown

Screen Recording 2020-10-11 at 8 16 35 PM

Feel free to suggest any changes (especially on the colors as I wasn't too sure what to use)!

### CODE REVIEW

**Comment by jayehernandez** [comment]
Thanks for this @reginaalyssa!! 🥳 Colors look good, I think we can just lower the opacity of the background color so that the white is easier on the eyes?

**Comment by reginaalyssa** [comment]
> Thanks for this @reginaalyssa!! 🥳 Colors look good, I think we can just lower the opacity of the background color so that the white is easier on the eyes?

Hi @jayehernandez noted on this! Updated the colors for the new components. Kindly see below for the new recording. 😊 

Screen Recording 2020-10-11 at 10 49 37 PM

**Review by jayehernandez — APPROVED** [review]

**Comment by jayehernandez** [comment]
Thank you for the screen recording!! this is good to go, will include in the next release. Thank you so much, @reginaalyssa! ❤️

**Comment by jayehernandez** [comment]
@all-contributors please add @reginaalyssa for code

**Pull request merged**
