### PR TITLE
Add thai language

### PR DESCRIPTION
**Pull request by itzmeowww**
## ✅ New Language Checklist
- [x] There is ❌ no assigned issue or pull request for this new language.
- [x] ➕ Added a new JSON object in the `server/data/languages.json` file.
- [x] Added the **voice** 🎤 attribute supported by ResponsiveVoice API.
- [x] Added the **flag** 🏳 attribute in the format of the twemoji-awesome CSS syntax.
- [ ] Added the **romanization** attribute for appropriate languages.
- [x] ➕ Created the `{language.json}` file inside the `server/data/words` folder containing the list of the 3000 words.
- [x] Removed duplicates and noted 🗒 them in the Pull Request.
- [x] Increment `currentLanguagesCount` in `client/src/store/index.js`
- [x] Add new language in `README.md`

### CODE REVIEW

**Comment by itzmeowww** [comment]
#1

**Comment by itzmeowww** [comment]
Can anyone help me with the check fail (🚥 Test / build (pull_request))

**Comment by Kvaibhav01** [comment]
Hey, @itzmeowww take a look at [this log](https://github.com/jayehernandez/letra-extension/pull/336/checks?check_run_id=1197721767#step:7:9). There seems to be some issue with the `response` variable in the _index.js_ file.

**Comment by itzmeowww** [comment]
@Kvaibhav01 Thanks, it was caused by my text formatting. 😄

**Review by jayehernandez — COMMENTED** [review]
Thanks for starting this out, @itzmeowww! Just wondering about the changes in the README file aside from adding Thai to the supported languages?

**Comment by itzmeowww** [comment]
> Thanks for starting this out, @itzmeowww! Just wondering about the changes in the README file aside from adding Thai to the supported languages? It's causing some merge conflicts

Ohh, I will try to fix it.

**Comment by itzmeowww** [comment]
@jayehernandez I think it is caused by the ALL-CONTRIBUTORS-BADGE part.

**Review by jayehernandez — APPROVED** [review]

**Comment by jayehernandez** [comment]
Thank you for contributing to Letra ☀️, @itzmeowww!! Appreciate your contribution to this open source project. 🥳

I'll be including the addition of Thai in the next release! 

---

Continue supporting Letra by:
- Leaving a star ⭐️ for this GitHub repository
- Downloading the free [Chrome extension](https://chrome.google.com/webstore/detail/letra/cjodkkjokggcaeacdhjliobekbnnmoio) and leaving a review
- Upvoting the [ProductHunt page](https://www.producthunt.com/posts/letra-2)

**Comment by jayehernandez** [comment]
@all-contributors please add @itzmeowww for translation

**Comment by kvharish** [comment]
Hi, @itzmeowww @jayehernandez I think incrementing the currentLanguagesCount is not done as part of this pull request. Could you please confirm? So that I can make the relevant change for the Tamil language pull request #376

**Comment by kvharish** [comment]
@itzmeowww  @jayehernandez  Yes just checked the number of JSON files inside server/data/words and there are 16 in master so I will change the currentLanguagesCount to 17 in my pull request.

**Comment by jayehernandez** [comment]
@kvharish thanks for noticing this!!

**Comment by kvharish** [comment]
Hi, @jayehernandez @itzmeowww I also noticed that the Thailand flag has a typo in the README.md file so I have raised a new pull request #381 to fix it.

**Comment by itzmeowww** [comment]
@kvharish Thanks 😁

**Pull request merged**
