### PR TITLE
Removed White Space

### PR DESCRIPTION
**Pull request by Mrskillful**
Removed the white space in :

"sentence": "Language is a system of signs expressive of ideas.",

### CODE REVIEW

**Comment by jayehernandez** [comment]
Thank you for contributing @Mrskillful, I'll be closig #222 as well as that seems to be a duplicate for this. :)

@all-contributors please add @Mrskillful for content

**Comment by jayehernandez** [comment]
Thanks for helping out in reviewing this as well @HarshPatel270698!

@all-contributors please add @HarshPatel270698 for review

**Comment by Mrskillful** [comment]
@jayehernandez Thanks for letting me help, I'll be sure to contribute more as necessary.

**Comment by jayehernandez** [comment]
> @jayehernandez Thanks for letting me help, I'll be sure to contribute more as necessary.

@Mrskillful glad to! You’re welcome to contribute and open new issues anytime :)

**Pull request merged**
