### PR TITLE
Test branch for Pull Request Template

### PR DESCRIPTION
**Pull request by jayehernandez**
## ✅ New Quote Checklist
- [ ] The quote(s) added are in alphabetical order and not ❌ duplicates.
- [ ] The quote(s) added are about **learning a foreign language**.
- [ ] The sentence attribute does not have inner quotation marks, and is ended with a period.
- [ ] Copy pasted the raw JSON `quotes.json` file to [JSONLint](https://jsonlint.com/) and made sure that the modified JSON file is valid.

## ✅ New Language Checklist
- [ ] There is ❌ no assigned issue or pull request for this new language.
- [ ] ➕ Added a new JSON object in the `server/data/languages.json` file.
- [ ] Added the **voice** 🎤 attribute supported by ResponsiveVoice API.
- [ ] Added the **flag** 🏳 atrribute in the format of the twemoji-awesome CSS syntax.
- [ ] Added the **romanization** atrribute for appropriate languages.
- [ ] ➕ Created the `{language.json}` file inside the `server/data/words` folder containing the list of the 3000 words.
- [ ] Removed duplicates and noted 🗒 them in the Pull Request.
- [ ] Increment `currentLanguagesCount` in `client/src/store/index.js`
- [ ] Add new language in `README.md`

### CODE REVIEW

**Comment by jayehernandez** [comment]
Hey @HarshPatel270698, had to move `PULL_REQUEST_TEMPLATE.md` to outside the PR template folder so that it will show  up as the default. Hope this is okay.

**Comment by HarshPatel270698** [comment]
To create multiple pull request templates and use the template query parameter to specify a template to fill the pull request body, type .github/PULL_REQUEST_TEMPLATE/, then the name of your pull request template. For example, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md. You can also store multiple pull request templates in a PULL_REQUEST_TEMPLATE subdirectory within the root or docs/ directories. For more information, see "About automation for issues and pull requests with query parameters." 

https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

**Comment by HarshPatel270698** [comment]
I was not sure about how many templates you want so opted for the way in which you can create multiple templates.

> 
> 
> To create multiple pull request templates and use the template query parameter to specify a template to fill the pull request body, type .github/PULL_REQUEST_TEMPLATE/, then the name of your pull request template. For example, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md. You can also store multiple pull request templates in a PULL_REQUEST_TEMPLATE subdirectory within the root or docs/ directories. For more information, see "About automation for issues and pull requests with query parameters."
> 
> https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

**Comment by jayehernandez** [comment]
@HarshPatel270698 yeah I also saw the multiple templates but it added work of having to place query parameters at the end of the pull request link (which I'm not sure people would do). :(

**Pull request merged**
