### PR TITLE
Sorted quotes.json major update

### PR DESCRIPTION
**Pull request by HarshPatel270698**
- Sorted quotes.json using https://novicelab.org/jsonabc/ to prevent checking and addition of new quotes duplicates
- Modified Adding Quote Example according to new JSON structure and updated checklist in docs/new_quote.md

### CODE REVIEW

**Comment by jayehernandez** [comment]
Thanks for initiating this @HarshPatel270698! Agree that the order should be alphabetical. Hope you can resolve the conflicts from the recent quotes PR though. Thank you!

**Comment by HarshPatel270698** [comment]
Added changes of #224 kindly double-check it.

**Comment by HarshPatel270698** [comment]
@jayehernandez **kindly review all changes and approve this commit before someone commit in quotes.json :)**

**Comment by jayehernandez** [comment]
Merged this as soon as I saw, glad that no one opened new PRs lol 😅

Thank you for initiating this again, @HarshPatel270698. @all-contributors please add @HarshPatel270698 for content

**Pull request merged**
